FROM python:3.7.0
MAINTAINER test
EXPOSE 9090
ADD ./requirements.txt /home/
RUN pip install -r /home/requirements.txt -i https://pypi.douban.com/simple/ 
RUN pip install uwsgi -i https://pypi.douban.com/simple/
VOLUME ["/home"]
WORKDIR /home/demo
CMD ["uwsgi", "--ini", "/home/demo/uwsgi.ini"] 