# Generated by Django 3.2.10 on 2022-08-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0002_modulw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modulw',
            new_name='Module',
        ),
    ]
