# Generated by Django 3.2.10 on 2022-08-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0004_moduletest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleTest',
        ),
    ]
