# Generated by Django 3.2.10 on 2022-08-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0007_casesuite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casesuite',
            options={'verbose_name': '测试集合表', 'verbose_name_plural': '测试集合表'},
        ),
    ]
