# Generated by Django 3.2.10 on 2022-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0008_alter_casesuite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesuite',
            name='test_case_model',
            field=models.CharField(blank=True, help_text='data/keyword', max_length=100, null=True, verbose_name='测试执行模式'),
        ),
    ]
