# Generated by Django 3.2.10 on 2022-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0010_suitecase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(verbose_name='卡号')),
                ('card_user', models.CharField(max_length=128, verbose_name='姓名')),
                ('card_time', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '银行卡账户',
                'verbose_name_plural': '银行卡账户信息',
            },
        ),
    ]
