# Generated by Django 3.2.10 on 2022-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0011_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.IntegerField(choices=[(1, '普通会员'), (2, 'VIP'), (3, 'SVIP')], default=1, verbose_name='级别')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='TOKEN')),
            ],
        ),
    ]
