# Generated by Django 3.2.10 on 2022-10-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0013_auto_20221010_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='名称'),
        ),
    ]
