# Generated by Django 3.2.10 on 2022-10-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0016_department_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='interfacetestplatform.department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='interfacetestplatform.Role', verbose_name='角色'),
        ),
    ]
