# Generated by Django 3.2.10 on 2022-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0019_auto_20221010_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='文件')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '上传文件',
            },
        ),
    ]
