# Generated by Django 3.2.10 on 2022-11-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacetestplatform', '0020_upfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upfile',
            name='file',
            field=models.FileField(blank=True, upload_to='avatar/', verbose_name='文件'),
        ),
    ]
